[project]
name = 'Blockchain-Enabled-Rural-Skills-Preservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.documentation]
path = 'contracts/documentation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
